### ISSUE TITLE
Support `load`ing while already in a tmux session

### ISSUE THREAD

**Issue by coreyja** [brianp/muxed#49]
## System Info
OS: Mac OS 10.15.2
Muxed Version: v0.8.0

## Description
When already inside a tmux session, `muxed` errors with a warning from `tmux` about nested sessions.
`sessions should be nested with care, unset $TMUX to force`

## Steps to reproduce

- tmux
- muxed new test
- muxed test

#### Expected
Muxed creates a detached session and switches tmux to that session

#### Actual
A tmux error message is printed to the terminal
`sessions should be nested with care, unset $TMUX to force`

## Use Case

I have my terminal default to opening a tmux session, so I am almost never in a `bare` bash terminal. This reduces the usability to `muxed` since it can't be used to load a new project while in a tmux session.

**Comment by brianp** [comment]
Hey @coreyja!

Thanks for giving Muxed a try. I too have seen this circumstance and generally thought "oh yeah I guess I *should* nest with care" and never really considered it more __but__ I think your use case is entirely valid and also something I should consider doing myself.

I'm going to look to fix this. I'll ping back here once a PR is merged, and release produced.

Cheers, and thanks again!

**Comment by brianp** [comment]
The [0.8.1 tag](https://github.com/brianp/muxed/tree/0.8.1) is up if you're building from source, or available on [homebrew](https://github.com/brianp/homebrew-muxed/), and [the releases page](https://github.com/brianp/muxed/releases/tag/0.8.1).

Let me know if it doesn't behave as expected. Right after the initial implementation I thought to myself "Oh yeah this is a quality of life improvement" haha. I hadn't realized how natural it had become for me to work around this before.

**Comment by coreyja** [comment]
🎉 🎉 🎉 

Oh this is great!! Thanks for getting this released! Just pulled the new release and it worked exactly as expected!

I'll let you know if I run into any issues or see anything weird!

Thanks again!
